import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SelectedElementProvider } from "@/context/SelectedElement";
import { ContentProvider } from "@/context/CreateContext";
import { ElementsProvider } from "@/context/ElementsContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContentProvider>
       

         <ElementsProvider>
                 <SelectedElementProvider>
        {children}
       </SelectedElementProvider>
  
         </ElementsProvider>
 
        </ContentProvider>
      
      </body>
    </html>
  );
}
