import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SelectedElementProvider } from "@/context/SelectedElement";
import { ContentProvider } from "@/context/CreateContext";
import { ElementsProvider } from "@/context/ElementsContext";
import { BoxProvider } from "@/context/BoxContext";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { ImageBoxProvider } from "@/context/ImageBox";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable}`}
      >
        <ContentProvider>
          <BoxProvider>

            <ElementsProvider>
              <SelectedElementProvider>
                <ImageBoxProvider>
                  {children}
                </ImageBoxProvider>
              </SelectedElementProvider>

            </ElementsProvider>
          </BoxProvider>
        </ContentProvider>

      </body>
    </html>
  );
}
